const buildMachine = ({ id, name, section }, index) => ({
  id,
  machineCode: id,
  name,
  section,
  department: section,
  area: '',
  manufacturer: '',
  model: '',
  serialNumber: '',
  installDate: '',
  powerRating: '',
  voltage: '',
  current: '',
  runningHours: 0,
  criticality: '',
  status: 'running',
  docs: [],
  spares: [],
  photos: [],
  createdAt: new Date(Date.UTC(2026, 0, 1, 8, index, 0)).toISOString(),
});

export const EQUIPMENT_REGISTER = [
  { id: 'MC-001', name: 'Solvent Transfer Pump 1-UG', section: 'Formulation Park' },
  { id: 'MC-002', name: 'Solvent Transfer Pump 2-UG', section: 'Formulation Park' },
  { id: 'MC-003', name: 'ACM-H Blower Fan', section: 'Herbi ACM Formulation' },
  { id: 'MC-004', name: 'ACM-H Pre Blender -1', section: 'Herbi ACM Formulation' },
  { id: 'MC-005', name: 'ACM-H Post Blender-1', section: 'Herbi ACM Formulation' },
  { id: 'MC-006', name: 'ACM30-H', section: 'Herbi ACM Formulation' },
  { id: 'MC-007', name: 'ACM-H Bag filter', section: 'Herbi ACM Formulation' },
  { id: 'MC-008', name: 'ACM-H Pre Blender-2', section: 'Herbi ACM Formulation' },
  { id: 'MC-009', name: 'ACM-H Post Blender-2', section: 'Herbi ACM Formulation' },
  { id: 'MC-010', name: 'FFS MC no. 14-Colline 20/80 gm (Prolific)', section: 'Herbi EC Packaging' },
  { id: 'MC-011', name: 'SS Slat Conveyor No.3', section: 'Herbi EC Packaging' },
  { id: 'MC-012', name: 'Induction Sealer No.7', section: 'Herbi EC Packaging' },
  { id: 'MC-013', name: 'Induction Sealer No.8', section: 'Herbi EC Packaging' },
  { id: 'MC-014', name: 'Induction Sealer No.9', section: 'Herbi EC Packaging' },
  { id: 'MC-015', name: 'Induction Sealer No.10', section: 'Herbi EC Packaging' },
  { id: 'MC-016', name: 'Shrink Wrapping Machine No 6', section: 'Herbi EC Packaging' },
  { id: 'MC-017', name: 'Shrink Wrapping Machine No 7', section: 'Herbi EC Packaging' },
  { id: 'MC-018', name: 'Shrink Wrapping Machine No 8', section: 'Herbi EC Packaging' },
  { id: 'MC-019', name: 'Carton Tapping Machine No.10', section: 'Herbi EC Packaging' },
  { id: 'MC-020', name: 'Carton Tapping Machine No.12', section: 'Herbi EC Packaging' },
  { id: 'MC-021', name: 'Auto Capping Machine With cap dispenser', section: 'Herbi EC Packaging' },
  { id: 'MC-022', name: 'FFS Machine No. 13 Surfactant packing', section: 'Herbi EC Packaging' },
  { id: 'MC-023', name: 'Liquid Filling Machine No.4(2H)', section: 'Herbi EC Packaging' },
  { id: 'MC-024', name: 'Labeling Machine No. 5', section: 'Herbi EC Packaging' },
  { id: 'MC-025', name: 'Labeling Machine No. 6', section: 'Herbi EC Packaging' },
  { id: 'MC-026', name: 'Shrink Wrapping Machine No 9', section: 'Herbi EC Packaging' },
  { id: 'MC-027', name: 'Carton Tapping Machine No.11', section: 'Herbi EC Packaging' },
  { id: 'MC-028', name: 'Liquid Filling Machine No.5(6H)', section: 'Herbi EC Packaging' },
  { id: 'MC-029', name: 'Semi Automatic plug pressing machine No', section: 'Herbi EC Packaging' },
  { id: 'MC-030', name: 'ROPP TIN Cap Sealer No. 4', section: 'Herbi EC Packaging' },
  { id: 'MC-031', name: 'Auto ScrewCappingM/c SingleHead 01', section: 'Herbi EC Packaging' },
  { id: 'MC-032', name: 'Strapping machine No 3', section: 'Herbi EC Packaging' },
  { id: 'MC-033', name: 'Induction Sealing MC with Rej.-01', section: 'Herbi EC Packaging' },
  { id: 'MC-034', name: 'AODD Pump No.3 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-035', name: 'Solvent Transfer Pump 1-AG', section: 'EC Herbi Formulation' },
  { id: 'MC-036', name: 'Solvent Transfer Pump 2-AG', section: 'EC Herbi Formulation' },
  { id: 'MC-037', name: 'Centrifugal Pump MIPA', section: 'EC Herbi Formulation' },
  { id: 'MC-038', name: 'Formulation Tank No. 2 -5Kl', section: 'EC Herbi Formulation' },
  { id: 'MC-039', name: 'Formulation Tank No. 4 -2KL', section: 'EC Herbi Formulation' },
  { id: 'MC-040', name: 'Gear Pump No.1 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-041', name: 'Gear Pump No.2 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-042', name: 'Gear Pump No.6 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-043', name: 'SS Solvent Tank 1KL MIPA-No2', section: 'EC Herbi Formulation' },
  { id: 'MC-044', name: 'Screw Pump No. 3 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-045', name: 'Filter Press with Pump No.2-36inch', section: 'EC Herbi Formulation' },
  { id: 'MC-046', name: 'Formulation Tank No 5 -5KL', section: 'EC Herbi Formulation' },
  { id: 'MC-047', name: 'DM Water Pump', section: 'EC Herbi Formulation' },
  { id: 'MC-048', name: 'Formulation Tank No. 1- 2Kl', section: 'EC Herbi Formulation' },
  { id: 'MC-049', name: 'Formulation Tank No. 3 -4KL', section: 'EC Herbi Formulation' },
  { id: 'MC-050', name: 'Gear Pump No.3 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-051', name: 'Gear Pump No.4 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-052', name: 'Gear Pump No.5 SL', section: 'EC Herbi Formulation' },
  { id: 'MC-053', name: 'SS Solvent Tank 1KL MIPA-No1', section: 'EC Herbi Formulation' },
  { id: 'MC-054', name: 'MS Solvent Tank 7KL C9-No3', section: 'EC Herbi Formulation' },
  { id: 'MC-055', name: 'Electric Wire rope Hoist No. 5', section: 'EC Herbi Formulation' },
  { id: 'MC-056', name: 'In Line Homonizer Pump 2', section: 'EC Herbi Formulation' },
  { id: 'MC-057', name: 'Bulk Storage tank AG 18KL -No.-7', section: 'EC Herbi Formulation' },
  { id: 'MC-058', name: 'SFG Storage Tank No 1-4KL', section: 'EC Herbi Formulation' },
  { id: 'MC-059', name: 'Sparkler filter 01', section: 'EC Herbi Formulation' },
  { id: 'MC-060', name: 'Volumetric filler with conveyor 60gm 02', section: 'EC Herbi Formulation' },
  { id: 'MC-061', name: 'Dyno Mill No. 1 30ltr', section: 'SC Herbicide Formulation' },
  { id: 'MC-062', name: 'Vertical Dynomill no. 1', section: 'SC Herbicide Formulation' },
  { id: 'MC-063', name: 'Vertical Dynomill no. 2', section: 'SC Herbicide Formulation' },
  { id: 'MC-064', name: 'Homognizer pump Vertical dynomill-01', section: 'SC Herbicide Formulation' },
  { id: 'MC-065', name: 'Homognizer Pump Vertical dynomill-02', section: 'SC Herbicide Formulation' },
  { id: 'MC-066', name: 'Pre-Mixing Vessel No.1(3.5kl) Gly', section: 'SC Herbicide Formulation' },
  { id: 'MC-067', name: 'Pre-Mixing Vessel No.2(3.5kl) Gly', section: 'SC Herbicide Formulation' },
  { id: 'MC-068', name: 'Post-Mixing Vessel No.1(5kl) Gly', section: 'SC Herbicide Formulation' },
  { id: 'MC-069', name: 'Post-Mixing Vessel No.2(5kl) Gly', section: 'SC Herbicide Formulation' },
  { id: 'MC-070', name: '1In AODD pump PP -03', section: 'SC Herbicide Formulation' },
  { id: 'MC-071', name: '1In AODD pump PP -04', section: 'SC Herbicide Formulation' },
  { id: 'MC-072', name: 'Liquid Filling Machine 4-H(GMP)', section: 'SC Herbicide Packaging' },
  { id: 'MC-073', name: 'Auto Capping machine single head 01', section: 'SC Herbicide Packaging' },
  { id: 'MC-074', name: 'FFS MC no. 16-MHW Topper(Prolific)', section: 'SC Herbicide Packaging' },
  { id: 'MC-075', name: 'Induction Sealing MC with Rej.-02', section: 'SC Herbicide Packaging' },
  { id: 'MC-076', name: 'Extruder No.2', section: 'Topper Formulation Herbi' },
  { id: 'MC-077', name: 'FBD No.1 120Kg', section: 'Topper Formulation Herbi' },
  { id: 'MC-078', name: 'Vibatory Screen No 4', section: 'Topper Formulation Herbi' },
  { id: 'MC-079', name: 'Vibro Screen No 1', section: 'Topper Formulation Herbi' },
  { id: 'MC-080', name: 'Extruder No. 3', section: 'Topper Formulation Herbi' },
  { id: 'MC-081', name: 'Sigma Mixer', section: 'Topper Formulation Herbi' },
  { id: 'MC-082', name: 'Screw conveyor', section: 'Herbi Packaging' },
  { id: 'MC-083', name: 'FFS Machine No. 12 Atrazine', section: 'Herbi Packaging' },
  { id: 'MC-084', name: 'FFS machine No.11 8gm', section: 'Herbi Packaging' },
  { id: 'MC-085', name: 'Volumetric filler with conveyor 60gm 01', section: 'Herbi Packaging' },
  { id: 'MC-086', name: 'ACM I Blower Fan', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-087', name: 'ACM-I Bag filter', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-088', name: 'ACM30-I', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-089', name: 'Electric Chain Hoist No. 3', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-090', name: 'ACM-I Pre Blender -1', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-091', name: 'ACM-I Post Blender-1', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-092', name: 'ACM-I Pre Blender-2', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-093', name: 'ACM-I Post Blender-2', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-094', name: 'FBD No. 03 -300Kg(GMP)', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-095', name: 'Extruder No. 04 (300kg GMP)', section: 'ACM-1 INSEC Formulation' },
  { id: 'MC-096', name: 'SS Slat Conveyor No.2', section: 'EC INSEC Packaging' },
  { id: 'MC-097', name: 'FFS Machine No.14 5ml', section: 'EC INSEC Packaging' },
  { id: 'MC-098', name: 'Rovo filler No. 1', section: 'EC INSEC Packaging' },
  { id: 'MC-099', name: 'Rovo filler No. 3', section: 'EC INSEC Packaging' },
  { id: 'MC-100', name: 'Induction Sealer No. 1', section: 'EC INSEC Packaging' },
  { id: 'MC-101', name: 'Induction Sealer No. 2', section: 'EC INSEC Packaging' },
  { id: 'MC-102', name: 'Induction Sealer No. 3', section: 'EC INSEC Packaging' },
  { id: 'MC-103', name: 'Induction Sealer No. 4', section: 'EC INSEC Packaging' },
  { id: 'MC-104', name: 'Labeling Machine No. 2', section: 'EC INSEC Packaging' },
  { id: 'MC-105', name: 'Labeling Machine No. 3', section: 'EC INSEC Packaging' },
  { id: 'MC-106', name: 'ROPP TIN Cap Sealer No. 1', section: 'EC INSEC Packaging' },
  { id: 'MC-107', name: 'ROPP TIN Cap Sealer No.3', section: 'EC INSEC Packaging' },
  { id: 'MC-108', name: 'Shrink Wrapping Machine No 4', section: 'EC INSEC Packaging' },
  { id: 'MC-109', name: 'Shrink Wrapping Machine No 5', section: 'EC INSEC Packaging' },
  { id: 'MC-110', name: 'Carton Tapping Machine No.1', section: 'EC INSEC Packaging' },
  { id: 'MC-111', name: 'Carton Tapping Machine No.3', section: 'EC INSEC Packaging' },
  { id: 'MC-112', name: 'Carton Tapping Machine No.4', section: 'EC INSEC Packaging' },
  { id: 'MC-113', name: 'Carton Tapping Machine No.6', section: 'EC INSEC Packaging' },
  { id: 'MC-114', name: 'Auto Capping Machine with Cap dispenser', section: 'EC INSEC Packaging' },
  { id: 'MC-115', name: 'Ink Jet Printer No.1 AJ', section: 'EC INSEC Packaging' },
  { id: 'MC-116', name: 'Liquid Filling Machine No. 1 (8H)', section: 'EC INSEC Packaging' },
  { id: 'MC-117', name: 'Liquid Filling Machine No. 2 (8H)', section: 'EC INSEC Packaging' },
  { id: 'MC-118', name: 'SS Slat Conveyor No.1', section: 'EC INSEC Packaging' },
  { id: 'MC-119', name: 'Rovo filler No. 2', section: 'EC INSEC Packaging' },
  { id: 'MC-120', name: 'Induction Sealer No. 5', section: 'EC INSEC Packaging' },
  { id: 'MC-121', name: 'Induction sealer No. 6', section: 'EC INSEC Packaging' },
  { id: 'MC-122', name: 'Labeling Machine No. 1', section: 'EC INSEC Packaging' },
  { id: 'MC-123', name: 'ROPP TIN Cap Sealer No.2', section: 'EC INSEC Packaging' },
  { id: 'MC-124', name: 'ROPP AL Cap Sealer No.1', section: 'EC INSEC Packaging' },
  { id: 'MC-125', name: 'Shrink Wrapping Machine No 1', section: 'EC INSEC Packaging' },
  { id: 'MC-126', name: 'Shrink Wrapping Machine No 2', section: 'EC INSEC Packaging' },
  { id: 'MC-127', name: 'Shrink Wrapping Machine No 3', section: 'EC INSEC Packaging' },
  { id: 'MC-128', name: 'Carton Tapping Machine No.2', section: 'EC INSEC Packaging' },
  { id: 'MC-129', name: 'Carton Tapping Machine No.5', section: 'EC INSEC Packaging' },
  { id: 'MC-130', name: 'Auto Capping Machine with Cap dispenser', section: 'EC INSEC Packaging' },
  { id: 'MC-131', name: 'Liquid Filling Machine No. 3 (8H)', section: 'EC INSEC Packaging' },
  { id: 'MC-132', name: 'Rewinder No.1', section: 'EC INSEC Packaging' },
  { id: 'MC-133', name: 'Ink Jet Conveyor No.1', section: 'EC INSEC Packaging' },
  { id: 'MC-134', name: 'Cut Pouch Conveyor No.1', section: 'EC INSEC Packaging' },
  { id: 'MC-135', name: 'ROPP AL Cap Sealer No.2', section: 'EC INSEC Packaging' },
  { id: 'MC-136', name: 'Strapping machine No 2', section: 'EC INSEC Packaging' },
  { id: 'MC-137', name: 'ROPP AL Cap Sealer No.3', section: 'EC INSEC Packaging' },
  { id: 'MC-138', name: 'Strapping machine No 1', section: 'EC INSEC Packaging' },
  { id: 'MC-139', name: 'Shrink Wrapping Machine No 10', section: 'EC INSEC Packaging' },
  { id: 'MC-140', name: 'Induction Sealing MC with Rej.-03', section: 'EC INSEC Packaging' },
  { id: 'MC-141', name: 'AODD Pump No.1 EC', section: 'EC INSEC FORMULATION' },
  { id: 'MC-142', name: 'Bulk Storage tank UG 20KL -No.-3', section: 'EC INSEC FORMULATION' },
  { id: 'MC-143', name: 'Water Bath Pump', section: 'EC INSEC FORMULATION' },
  { id: 'MC-144', name: 'Formulation Tank No. 3(3KL) HDPE', section: 'EC INSEC FORMULATION' },
  { id: 'MC-145', name: 'Formulation Tank No.4(5KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-146', name: 'Gear Pump No.1 EC', section: 'EC INSEC FORMULATION' },
  { id: 'MC-147', name: 'Gear Pump No.2 EC', section: 'EC INSEC FORMULATION' },
  { id: 'MC-148', name: 'Gear Pump No.3 EC', section: 'EC INSEC FORMULATION' },
  { id: 'MC-149', name: 'Solvent Storage Tank No.3(1KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-150', name: 'Solvent Storage Tank No.4(1KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-151', name: 'Filter Press with Pump No.1-14inch', section: 'EC INSEC FORMULATION' },
  { id: 'MC-152', name: 'Electric Wire rope Hoist No. 1', section: 'EC INSEC FORMULATION' },
  { id: 'MC-153', name: 'Formulation Tank No.1(10KL) SS', section: 'EC INSEC FORMULATION' },
  { id: 'MC-154', name: 'SFG Storage Tank No.6(5KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-155', name: 'Water Bath', section: 'EC INSEC FORMULATION' },
  { id: 'MC-156', name: 'Bulk Storage tank UG 25KL -No.-2', section: 'EC INSEC FORMULATION' },
  { id: 'MC-157', name: 'Bulk Storage tank AG 18KL -No.-6', section: 'EC INSEC FORMULATION' },
  { id: 'MC-158', name: 'Solvent Transfer Pump 3-AG', section: 'EC INSEC FORMULATION' },
  { id: 'MC-159', name: 'Solvent Storage Tank No.1(8.5KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-160', name: 'Solvent Storage Tank No.2(3.5KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-161', name: 'Formulation Tank No. 2(5KL) SS', section: 'EC INSEC FORMULATION' },
  { id: 'MC-162', name: 'SFG Storage Tank no.1(5KL) Horizonal', section: 'EC INSEC FORMULATION' },
  { id: 'MC-163', name: 'AODD Pump No.2 EC', section: 'EC INSEC FORMULATION' },
  { id: 'MC-164', name: 'Bulk Storage tank UG 20KL -No.-4', section: 'EC INSEC FORMULATION' },
  { id: 'MC-165', name: 'SFG Storage Tank no.2(5KL) Horizonal', section: 'EC INSEC FORMULATION' },
  { id: 'MC-166', name: 'SFG Storage Tank no.3(5KL) Horizonal', section: 'EC INSEC FORMULATION' },
  { id: 'MC-167', name: 'SFG Storage Tank no.4(5KL) Horizonal', section: 'EC INSEC FORMULATION' },
  { id: 'MC-168', name: 'SFG Storage Tank No.5(10KL)', section: 'EC INSEC FORMULATION' },
  { id: 'MC-169', name: 'Bulk Storage tank UG 25KL -No.-1', section: 'EC INSEC FORMULATION' },
  { id: 'MC-170', name: 'Bulk Storage tank AG 18KL -No.-5', section: 'EC INSEC FORMULATION' },
  { id: 'MC-171', name: 'Stacker No. 1', section: 'Finish Goods' },
  { id: 'MC-172', name: 'Electric Stacker', section: 'Finish Goods' },
  { id: 'MC-173', name: 'Blower Fan DC No.2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-174', name: 'Dye Mixer No.4', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-175', name: 'Gear Pump No.1 GR', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-176', name: 'Sand Hopper No. 1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-177', name: 'Sand Hopper No. 2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-178', name: 'Sand Hopper No. 3', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-179', name: 'Bucket Elevator P 2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-180', name: 'Bucket Elevator P 3', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-181', name: 'Bucket Elevator S1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-182', name: 'Bucket Elevator S2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-183', name: 'Nauta Mixer No.1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-184', name: 'Nauta Mixer No.3', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-185', name: 'Vibatory Screen No 1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-186', name: 'Vibatory Screen No 3', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-187', name: 'Blower Fan DC No.1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-188', name: 'Bucket Elevator P 1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-189', name: 'Bucket Elevator S3', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-190', name: 'Electric Wire rope Hoist No. 4', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-191', name: 'Nauta Mixer No.2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-192', name: 'Vibatory Screen No 2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-193', name: 'Dust Collector No 1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-194', name: 'Dust Collector No 2', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-195', name: 'Dye Mixer No.1', section: 'CARTAP FORMULATION INSEC' },
  { id: 'MC-196', name: 'Carton Tapping Machine No.7', section: 'CARTAP PACKAGING INSEC' },
  { id: 'MC-197', name: 'Carton Tapping Machine No.9', section: 'CARTAP PACKAGING INSEC' },
  { id: 'MC-198', name: 'FFS Machine No.3 Carbofuran packing', section: 'CARTAP PACKAGING INSEC' },
  { id: 'MC-199', name: 'Bag Closing Machine No. 1', section: 'CARTAP PACKAGING INSEC' },
  { id: 'MC-200', name: 'Carton Tapping Machine No.8', section: 'CARTAP PACKAGING INSEC' },
  { id: 'MC-201', name: 'Ink Jet Conveyor No.2', section: 'CARTAP PACKAGING INSEC' },
  { id: 'MC-202', name: 'Jetmil Blower fan', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-203', name: 'Jetmill Bag filter', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-204', name: 'Jetmill Pre Blender 1', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-205', name: 'Jetmill Post Blender 1', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-206', name: 'Jetmill Pre Blender 2', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-207', name: 'Jetmill Post Blender 2', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-208', name: 'Padel Mixer 1', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-209', name: 'Jet Mill', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-210', name: 'Blower Fan DC No.3', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-211', name: 'Extruder No.1', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-212', name: 'Vibro Screen No 2', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-213', name: 'FBD No.2 150KG', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-214', name: 'Dust Collector No. 3', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-215', name: 'FFS MC no. 15-MHW Kohlar (Prolific)', section: 'JET MILL FORMULATION INSEC' },
  { id: 'MC-216', name: 'Zebra Printer', section: 'PRINTING SECTION EC' },
  { id: 'MC-217', name: 'Cut Pouch Conveyor No.3', section: 'PRINTING SECTION EC' },
  { id: 'MC-218', name: 'Cut Pouch Conveyor No.4', section: 'PRINTING SECTION EC' },
  { id: 'MC-219', name: 'Cut Pouch Conveyor No.2', section: 'PRINTING SECTION EC' },
  { id: 'MC-220', name: 'Ink Jet Conyevor No.3', section: 'PRINTING SECTION EC' },
  { id: 'MC-221', name: 'Rewinder No.2', section: 'PRINTING SECTION EC' },
  { id: 'MC-222', name: 'Cut Pouch Conveyor No.5', section: 'PRINTING SECTION EC' },
  { id: 'MC-223', name: 'Rewinder No.3 (central loading)', section: 'PRINTING SECTION EC' },
  { id: 'MC-224', name: 'Gear Pump No.5 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-225', name: 'Gear Pump No.6 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-226', name: 'Homogenizer vessel No. 1(2KL) Pre', section: 'SC INSEC FORMULATION' },
  { id: 'MC-227', name: 'Homogenizer vessel No. 2(3KL) Post', section: 'SC INSEC FORMULATION' },
  { id: 'MC-228', name: 'Dyno Mill No. 2 50ltr', section: 'SC INSEC FORMULATION' },
  { id: 'MC-229', name: 'Electric Wire rope Hoist No. 2', section: 'SC INSEC FORMULATION' },
  { id: 'MC-230', name: 'Homogenizer vessel No.3(3.5KL)Pre', section: 'SC INSEC FORMULATION' },
  { id: 'MC-231', name: 'In Line Homonizer Pump 1', section: 'SC INSEC FORMULATION' },
  { id: 'MC-232', name: 'In Line Homonizer Pump 3', section: 'SC INSEC FORMULATION' },
  { id: 'MC-233', name: 'Gear Pump No.1 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-234', name: 'Gear Pump No.2 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-235', name: 'Gear Pump No.3 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-236', name: 'Gear Pump No.4 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-237', name: 'Homogenizer vessel No.5(5KL) Post', section: 'SC INSEC FORMULATION' },
  { id: 'MC-238', name: 'Screw Pump No.1 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-239', name: 'Screw Pump No.2 SC', section: 'SC INSEC FORMULATION' },
  { id: 'MC-240', name: 'Dyno Mill No 4 100Ltr', section: 'SC INSEC FORMULATION' },
  { id: 'MC-241', name: 'Homogenizer vessel No.4(3.5KL)Pre', section: 'SC INSEC FORMULATION' },
  { id: 'MC-242', name: 'Homogenizer vessel No.6(5KL) Post', section: 'SC INSEC FORMULATION' },
  { id: 'MC-243', name: 'Gum mixer 1', section: 'SC INSEC FORMULATION' },
  { id: 'MC-244', name: 'Vertical Dynomill no. 3', section: 'SC INSEC FORMULATION' },
  { id: 'MC-245', name: 'FFS Machine No. 8 Crystocycline No-2', section: 'Acephate/Zivora Packaging INSEC' },
  { id: 'MC-246', name: 'Labeling Machine No. 4', section: 'Acephate/Zivora Packaging INSEC' },
  { id: 'MC-247', name: 'FFS MC No.17-Altrazine 500/1kg (Prolific)', section: 'Acephate/Zivora Packaging INSEC' },
  { id: 'MC-248', name: 'Fork Lift No. 3', section: 'STORE' },
  { id: 'MC-249', name: 'Fork Lift No. 2', section: 'STORE' },
  { id: 'MC-250', name: 'Fork Lift No. 1', section: 'STORE' },
  { id: 'MC-251', name: 'Fork Lift No. 04 -3MT(Godrej)', section: 'STORE' },
  { id: 'MC-252', name: 'Rotary Air Compressor No.1', section: 'Utility Section' },
  { id: 'MC-253', name: 'Rotary Air Compressor No.3', section: 'Utility Section' },
  { id: 'MC-254', name: 'Rotary Air Compressor no. 2', section: 'Utility Section' },
  { id: 'MC-255', name: 'ETP Plant 5KLD with evaporator', section: 'Utility Section' },
  { id: 'MC-256', name: 'STP Plant 8KLD', section: 'Utility Section' },
  { id: 'MC-257', name: 'DG operated pump', section: 'Utility Section' },
  { id: 'MC-258', name: 'Main Hyd. Pump', section: 'Utility Section' },
  { id: 'MC-259', name: 'Jockey Pump', section: 'Utility Section' },
  { id: 'MC-260', name: 'RO Plant-1 500LPH', section: 'Utility Section' },
  { id: 'MC-261', name: 'Rooftop Solar 260KW', section: 'Utility Section' },
  { id: 'MC-262', name: 'Rooftop Solar 240KW', section: 'Utility Section' },
  { id: 'MC-263', name: 'Water Chiller 1KL', section: 'Utility Section' },
  { id: 'MC-264', name: 'Waste Water Pump No.1', section: 'Utility Section' },
  { id: 'MC-265', name: 'Waste Water Pump No.2', section: 'Utility Section' },
  { id: 'MC-266', name: 'Automatic Voltage Controller No 1 600KVA', section: 'Utility Section' },
  { id: 'MC-267', name: 'DG set No.2 380KVA', section: 'Utility Section' },
  { id: 'MC-268', name: 'D.G. Set No.1 125KVA', section: 'Utility Section' },
  { id: 'MC-269', name: 'Transformer No 1 500KVA', section: 'Utility Section' },
  { id: 'MC-270', name: 'Automatic Voltage Controller No 2 300KVA', section: 'Utility Section' },
  { id: 'MC-271', name: 'Diesel Generator 500KVA', section: 'Utility Section' },
  { id: 'MC-272', name: 'Chiller Pump 3-SL', section: 'Utility Section' },
  { id: 'MC-273', name: 'Chiller Pump 4-SL', section: 'Utility Section' },
  { id: 'MC-274', name: 'Air cooled Scroll DX Chiller 48TR No 3', section: 'Utility Section' },
  { id: 'MC-275', name: 'Chiller Pump 1-SC', section: 'Utility Section' },
  { id: 'MC-276', name: 'Air cooled Scroll DX Chiller 24TR No 1', section: 'Utility Section' },
  { id: 'MC-277', name: 'Air cooled Scroll DX Chiller 24TR No 2', section: 'Utility Section' },
  { id: 'MC-278', name: 'Chiller Pump 2-SC', section: 'Utility Section' },
];

export const SEED_MACHINES = EQUIPMENT_REGISTER.map(buildMachine);
